stages:
  - deploy

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  - key:
      files:
        - package-lock.json
    paths:
      - .npm/

pages: # the job must be named pages
  image: node:18.18.0-slim
  stage: deploy
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - npm run build:gitlab
    # optionally, you can activate gzip support with the following line:
    - find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\)$' -exec gzip -f -k {} \;
  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public # artifact path must be /public for GitLab Pages to pick it up
  only:
    - master
